site_name: Evan Chauhan
site_url: https://mydomain.org/mysite
theme:
  name: material
  language: en
  icon: 
    features:
    - content.code.annotate #allows for annotations within code
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigaton.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight 
    - search.share
    - search.suggest 
